name: Format
on:
  push:
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    if: github.actor == 'shopify[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Node.js
        uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4
      - name: Cache node_modules
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Format files
        run: npm run fix:prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
        with:
          commit_message: Format files
